
jobs:

- name: copy_concourse_fetch_source_to_s3
  serial: true
  plan:

  - get: concourse_fetch_source
    trigger: true

  - get: concourse_fetch_source_semver
    params: {bump: minor}

  - task: create_concourse_fetch_source_tarball
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      inputs: 
      - name: concourse_fetch_source
      run:
        path: bash
        args:
        - -euc
        - |
          pushd concourse_fetch_source
          tar -cvf ../concourse_fetch_source_tarball/concourse_fetch_source.tar.gz *
          popd
      outputs:
      - name: concourse_fetch_source_tarball

  - task: push_concourse_fetch_source_tarball_to_s3
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      inputs: 
      - name: concourse_fetch_source_tarball
      run:
        path: bash
        args:
        - -euc
        - |
          export DEBIAN_FRONTEND=noninteractive
          export AWS_DEFAULT_REGION=((aws_default_region))
          export AWS_ACCESS_KEY_ID=((aws_access_key_id))
          export AWS_SECRET_ACCESS_KEY=((aws_secret_access_key))
          apt-get update -y
          apt-get install awscli -y
          aws sts get-caller-identity
          aws s3 cp concourse_fetch_source_tarball/concourse_fetch_source.tar.gz s3://((aws_s3_bucket_name))/

  - put: concourse_fetch_source_semver
    params: {bump: minor}

resources:

- name: concourse_fetch_source
  type: git
  source:
    branch: master
    private_key: ((github_private_key))
    uri: git@github.com:RealOrko/concourse-fetch.git


- name: concourse_fetch_source_semver
  type: semver
  source:
    driver: git
    branch: versions
    uri: git@github.com:RealOrko/concourse-fetch.git
    file: concourse_fetch_source_version
    private_key: |
      ((github_private_key))

